In [1]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
import pandas as pd
from datetime import datetime
import math
np.set_printoptions(precision=4)
import sys; sys.path.append('book_scripts')
%pwd

u'E:\\project\\pychram\\book_scripts'

In [2]:
def load_stock_base_msg():
    stock_data_path = 'E:/project/pychram/traderesp/base/output-csv/'
    stock_data_cvs = stock_data_path + 'output-2013-2014-all-stock-base-msg.csv'
    #
    stat = pd.read_csv(stock_data_cvs,encoding='gbk',index_col=['code'])
    return stat

In [3]:
def get_date_period_staticstics(begtime,endtime):
    #
    stock_data_path = 'E:/project/pychram/traderesp/strategy/output-csv/'
    stock_data_cvs = stock_data_path + 'output-stock-history-adjust-m26-kdj-' \
                                     + begtime.strftime('%Y%m%d') + '-' + endtime.strftime('%Y%m%d') + '.csv'
    #
    stat = pd.read_csv(stock_data_cvs,parse_dates=['buy_date','sell_date'],encoding='gbk')
    
    #逐笔利润
    stat['profit'] = stat['sell_price'] - stat['buy_price']
    #
    action_num = len(stat)
    suc_num = stat[stat['profit'] > 0.00 ].count() 
    fail_num = action_num - suc_num
    #
    tmp_profit = stat.groupby(['code']).sum()
    year_action_num = len(tmp_profit)
    tmp_profit['profit_rate'] = (tmp_profit['sell_price'] - tmp_profit['buy_price']) / tmp_profit['buy_price']
    year_suc_num = tmp_profit[tmp_profit['profit_rate'] > 0.00].count()
    year_fail_num = year_action_num - year_suc_num
    #
    year_suc_num_gt_percet_5 = tmp_profit[tmp_profit['profit_rate'] > 0.05].count()
    #
    stat_sum_all = stat.sum()
    code_unique_num = len(stat['code'].unique())
    s_ge_b_num = stat[stat['sell_price'] > stat['buy_price']].count()
    #
    print '-----  ',begtime,'  ----  ',endtime,'  -----'
    print '股票总数(排重) :',year_action_num
    print '买卖总次数(一次买卖算一次) :',action_num
    print '其中获利次数 :',suc_num['profit']
    print '其中亏损次数 :',fail_num['profit']
    print '获利次数比率 :',suc_num['profit'] / action_num
    print '亏损次数比率 :',fail_num['profit'] / action_num
    print '年度获利股票数 :',year_suc_num['profit_rate']
    print '年度亏损股票数 :',year_fail_num['profit_rate']
    print '年度获利股票数比率 :',year_suc_num['profit_rate'] / year_action_num
    print '年度亏损股票数比率 :',year_fail_num['profit_rate'] / year_action_num
    print '年度获利股票数( 盈利大于5%) :',year_suc_num_gt_percet_5['profit_rate']
    print '年度获利股票数比率( 盈利大于5%) :',year_suc_num_gt_percet_5['profit_rate'] / year_action_num
    print '---------------------------------------------------------------------'
    #
    return tmp_profit[tmp_profit['profit_rate'] > 0.00].sort_values('profit_rate',ascending=False),tmp_profit,stat

In [4]:
def show_date_staticstics():
    code1,code1_tmp1,code1_tmp2 = get_date_period_staticstics(datetime(2013,1,1),datetime(2013,12,31))
    code2,code2_tmp1,code2_tmp2 = get_date_period_staticstics(datetime(2014,1,1),datetime(2014,12,31))
    code3 = set(code1.index) & set(code2.index)
    year_2_num = len(code3)
    print '连续2年上涨股票数(获利股票数) :',year_2_num
    print '连续2年上涨股票数比率 :',year_2_num / len(code1) if len(code1) > 0 else 0
    #--------------------------------------------------------
    code1_gt_percent_5 =  code1[code1['profit_rate'] > 0.05]
    code2_gt_percent_5 =  code2[code2['profit_rate'] > 0.05]
    code3_gt_percent_5 =  set(code1_gt_percent_5.index) & set(code2_gt_percent_5.index)
    print '连续2年上涨股票数(获利股票数 大于 5%) :',len(code3_gt_percent_5)
    print '连续2年上涨股票数比率(获利大于 5%) :',len(code3_gt_percent_5) / len(code1) if len(code1) > 0 else 0
    #--------------------------------------------------------
    code4 = code1.index[0:100]
    code5 = code2.index[0:100]
    code6 = set(code4) & set(code5)
    year_2_num_from_100 = len(code6)
    print '连续2年上涨股票数(Top 100) :',year_2_num_from_100
    code7 = code1.index[0:200]
    code8 = code2.index[0:200]
    code9 = set(code7) & set(code8)
    year_2_num_from_200 = len(code9)
    print '连续2年上涨股票数(Top 200) :',year_2_num_from_200
    code10 = code1.index[0:300]
    code11 = code2.index[0:300]
    code12 = set(code10) & set(code11)
    year_2_num_from_300 = len(code12)
    print '连续2年上涨股票数(Top 300) :',year_2_num_from_300
    code13 = code1.index[0:400]
    code14 = code2.index[0:400]
    code15 = set(code13) & set(code14)
    year_2_num_from_400 = len(code15)
    print '连续2年上涨股票数(Top 400) :',year_2_num_from_400
    code16 = code1.index[0:500]
    code17 = code2.index[0:500]
    code18 = set(code16) & set(code17)
    year_2_num_from_500 = len(code18)
    print '连续2年上涨股票数(Top 500) :',year_2_num_from_500
    #
    code_bing = pd.merge(code1,code2,left_index=True, right_index=True)
    return code_bing,code_bing[(code_bing['profit_rate_x'] > 0.05) & (code_bing['profit_rate_y'] > 0.05)]

In [5]:
code_base_msg = load_stock_base_msg()
code_profit_rate_ge_0, code_profit_rate_ge_5 = show_date_staticstics()
code_profit_rate_ge_5 = code_profit_rate_ge_5[['profit_rate_x','profit_rate_y']]

-----   2013-01-01 00:00:00   ----   2013-12-31 00:00:00   -----
股票总数(排重) : 2468
买卖总次数(一次买卖算一次) : 68915
其中获利次数 : 31287
其中亏损次数 : 37628
获利次数比率 : 0.453994050642
亏损次数比率 : 0.546005949358
年度获利股票数 : 950
年度亏损股票数 : 1518
年度获利股票数比率 : 0.384927066451
年度亏损股票数比率 : 0.615072933549
年度获利股票数( 盈利大于5%) : 1
年度获利股票数比率( 盈利大于5%) : 0.000405186385737
---------------------------------------------------------------------
-----   2014-01-01 00:00:00   ----   2014-12-31 00:00:00   -----
股票总数(排重) : 2592
买卖总次数(一次买卖算一次) : 106587
其中获利次数 : 56329
其中亏损次数 : 50258
获利次数比率 : 0.528479082815
亏损次数比率 : 0.471520917185
年度获利股票数 : 2043
年度亏损股票数 : 549
年度获利股票数比率 : 0.788194444444
年度亏损股票数比率 : 0.211805555556
年度获利股票数( 盈利大于5%) : 22
年度获利股票数比率( 盈利大于5%) : 0.00848765432099
---------------------------------------------------------------------
连续2年上涨股票数(获利股票数) : 705
连续2年上涨股票数比率 : 0.742105263158
连续2年上涨股票数(获利股票数 大于 5%) : 0
连续2年上涨股票数比率(获利大于 5%) : 0.0
连续2年上涨股票数(Top 100) : 0
连续2年上涨股票数(Top 200) : 3
连续2年上涨股票数(Top 300) : 11
连续2年上涨股票数(Top 400) : 31
连续2年上涨股票数(Top 500) : 65

In [6]:
code_bing = pd.merge(code_base_msg,code_profit_rate_ge_5,left_index=True, right_index=True)

In [7]:
code_bing.columns

Index([    u'code_name',       u'sina_hy',       u'sina_gn',       u'sina_dy',
       u'profit_rate_x', u'profit_rate_y'],
      dtype='object')

In [8]:
def trim_float_num(x):
    #print type(x)
    #print 'x=',x
    xx = 0.000
    if x is None:
        xx = 0.000
    else:
        xx = float(str(x))
    # print xx
    if xx < 0.001:
        return "0.1 %"
    else:
        ret = '%.1f' %(xx * 100.00)
        return ret + ' %'

In [9]:
trim_profit_rate_x = code_bing['profit_rate_x'].map(trim_float_num)
code_bing['profit_rate_x'] = trim_profit_rate_x
trim_profit_rate_y = code_bing['profit_rate_y'].map(trim_float_num)
code_bing['profit_rate_y'] = trim_profit_rate_y

In [10]:
code_bing

Empty DataFrame
Columns: [code_name, sina_hy, sina_gn, sina_dy, profit_rate_x, profit_rate_y]
Index: []

In [11]:
code1,code_2,code_all = get_date_period_staticstics(datetime(2013,1,1),datetime(2013,12,31))

-----   2013-01-01 00:00:00   ----   2013-12-31 00:00:00   -----
股票总数(排重) : 2468
买卖总次数(一次买卖算一次) : 68915
其中获利次数 : 31287
其中亏损次数 : 37628
获利次数比率 : 0.453994050642
亏损次数比率 : 0.546005949358
年度获利股票数 : 950
年度亏损股票数 : 1518
年度获利股票数比率 : 0.384927066451
年度亏损股票数比率 : 0.615072933549
年度获利股票数( 盈利大于5%) : 1
年度获利股票数比率( 盈利大于5%) : 0.000405186385737
---------------------------------------------------------------------

In [1]:
code_all[code_all['code']==858]

NameError: name 'code_all' is not defined

In [13]:
code2,code21,code2_all = get_date_period_staticstics(datetime(2014,1,1),datetime(2014,12,31))

-----   2014-01-01 00:00:00   ----   2014-12-31 00:00:00   -----
股票总数(排重) : 2592
买卖总次数(一次买卖算一次) : 106587
其中获利次数 : 56329
其中亏损次数 : 50258
获利次数比率 : 0.528479082815
亏损次数比率 : 0.471520917185
年度获利股票数 : 2043
年度亏损股票数 : 549
年度获利股票数比率 : 0.788194444444
年度亏损股票数比率 : 0.211805555556
年度获利股票数( 盈利大于5%) : 22
年度获利股票数比率( 盈利大于5%) : 0.00848765432099
---------------------------------------------------------------------

In [14]:
code2_all[code2_all['code']==858]

,buy_date,buy_money,buy_num,buy_price,code,sell_date,sell_money,sell_num,sell_price,profit
1332,2014-02-11,23272.180995,100,232.721810,858,2014-02-17,25186.873837,100,251.868738,19.146928
4402,2014-02-18,24968.931818,100,249.689318,858,2014-02-24,24533.083155,100,245.330832,-4.358487
5736,2014-02-25,23521.240673,100,235.212407,858,2014-02-26,23505.669612,100,235.056696,-0.155711
7830,2014-03-04,24751.011316,100,247.510113,858,2014-03-05,25171.308239,100,251.713082,4.202969
11059,2014-03-25,26852.510274,100,268.525103,858,2014-03-31,25949.657771,100,259.496578,-9.028525
13107,2014-04-02,26899.220283,100,268.992203,858,2014-04-08,26805.840237,100,268.058402,-0.933800
15305,2014-04-09,26977.075944,100,269.770759,858,2014-04-14,27973.344060,100,279.733441,9.962681
17774,2014-04-15,27397.372906,100,273.973729,858,2014-04-17,27506.330482,100,275.063305,1.089576
19769,2014-04-18,27490.761899,100,274.907619,858,2014-04-22,26603.453464,100,266.034535,-8.873084
20956,2014-04-23,27553.010528,100,275.530105,858,2014-04-24,27817.657194,100,278.176572,2.646467
23307,2014-05-27,25871.872212,100,258.718722,858,2014-05-28,26214.338184,100,262.143382,3.424660
25910,2014-05-29,26136.507814,100,261.365078,858,2014-06-03,26011.953934,100,260.119539,-1.245539
27928,2014-06-04,25716.198017,100,257.161980,858,2014-06-05,26198.762473,100,261.987625,4.825645
30648,2014-06-06,26385.559649,100,263.855596,858,2014-06-11,27257.287880,100,272.572879,8.717282
33142,2014-06-12,27288.415703,100,272.884157,858,2014-06-17,26696.902869,100,266.969029,-5.915128
35548,2014-06-18,26728.031458,100,267.280315,858,2014-06-20,26525.653681,100,265.256537,-2.023778
37008,2014-07-01,27568.631032,100,275.686310,858,2014-07-02,27665.865594,100,276.658656,0.972346
39310,2014-07-03,28216.914305,100,282.169143,858,2014-07-08,28735.549346,100,287.355493,5.186350
39943,2014-07-09,28054.832917,100,280.548329,858,2014-07-10,28719.339690,100,287.193397,6.645068
42710,2014-07-15,31134.213962,100,311.342140,858,2014-07-21,30712.796934,100,307.127969,-4.214170
45280,2014-07-22,31587.988796,100,315.879888,858,2014-07-28,32447.012341,100,324.470123,8.590235
46940,2014-07-29,31652.839267,100,316.528393,858,2014-07-30,31166.620003,100,311.666200,-4.862193
49314,2014-07-31,31425.926282,100,314.259263,858,2014-08-05,31604.199896,100,316.041999,1.782736
50797,2014-08-06,31425.920604,100,314.259206,858,2014-08-11,31101.774144,100,311.017741,-3.241465
53330,2014-08-12,31085.570120,100,310.855701,858,2014-08-18,31814.917588,100,318.149176,7.293475
56021,2014-08-19,31588.013596,100,315.880136,858,2014-08-25,30583.155550,100,305.831556,-10.048580
58547,2014-08-26,30307.631902,100,303.076319,858,2014-08-29,30356.271578,100,303.562716,0.486397
60890,2014-09-01,30485.923214,100,304.859232,858,2014-09-09,31036.960559,100,310.369606,5.510373
63016,2014-09-10,31085.595476,100,310.855955,858,2014-09-12,30810.059593,100,308.100596,-2.755359
66873,2014-09-15,30583.143504,100,305.831435,858,2014-09-22,29318.954802,100,293.189548,-12.641887
69482,2014-09-23,29448.603220,100,294.486032,858,2014-09-29,29902.393525,100,299.023935,4.537903
71639,2014-09-30,29934.807720,100,299.348077,858,2014-10-08,29756.516005,100,297.565160,-1.782917
74472,2014-10-09,30177.898028,100,301.778980,858,2014-10-14,29075.766834,100,290.757668,-11.021312
76788,2014-10-15,28816.440070,100,288.164401,858,2014-10-20,28929.911963,100,289.299120,1.134719
78579,2014-10-21,28670.584232,100,286.705842,858,2014-10-22,28395.059918,100,283.950599,-2.755243
81035,2014-10-30,28070.920751,100,280.709208,858,2014-11-04,28168.164771,100,281.681648,0.972440
83567,2014-11-05,27892.651951,100,278.926520,858,2014-11-10,29108.177325,100,291.081773,12.155254
86403,2014-11-11,29010.926904,100,290.109269,858,2014-11-17,29140.623828,100,291.406238,1.296969
88393,2014-11-18,28605.776819,100,286.057768,858,2014-11-19,28362.656321,100,283.626563,-2.431205
90703,2014-11-20,28362.656321,100,283.626563,858,2014-11-25,29108.165598,100,291.081656,7.455093
91358,2014-11-26,29416.100882,100,294.161009,858,2014-12-01,30550.587535,100,305.505875,11.344867
93971,2014-12-02,30664.052417,100,306.640524,858,2014-12-08,32787.186491,100,327.871865,21.231341
95900,2014-12-09,31993.048047,100,319.930480,858,2014-12-10,33338.259738,100,333.382597,13.452117
98243,2014-12-11,32981.707051,100,329.817071,858,2014-12-16,32852.047589,100,328.520476,-1.296595
99704,2014-12-17,32382.033344,100,323.820333,858,2014-12-22,34521.384445,100,345.213844,21.393511
101999,2014-12-23,35218.302154,100,352.183022,858,2014-12-29,35088.622214,100,350.886222,-1.296799
104587,2014-12-30,34553.801434,100,345.538014,858,2014-12-31,34845.539180,100,348.455392,2.917377

In [15]:
code21.ix[858]

buy_money      1360213.357812
buy_num           4700.000000
buy_price        13602.133578
sell_money     1369962.657971
sell_num          4700.000000
sell_price       13699.626580
profit              97.493002
profit_rate          0.007167
Name: 858, dtype: float64